'use client';

import { useState, useRef, useEffect } from 'react';
import ReactMarkdown from 'react-markdown';

interface PolicySource {
  filename: string;
  content_snippet: string;
  similarity_score: number;
}

interface Message {
  role: 'user' | 'bot';
  content: string;
  sources?: PolicySource[];
  isSensitive?: boolean;
  modelUsed?: string;
}

export default function Home() {
  const [messages, setMessages] = useState<Message[]>([
    { role: 'bot', content: 'Hello! I am PolicyLens, your AI assistant. Ask me anything about company policies.' }
  ]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isLoading) return;

    const userMessage = input;
    setInput('');
    setMessages(prev => [...prev, { role: 'user', content: userMessage }]);
    setIsLoading(true);

    try {
      const res = await fetch('http://localhost:8000/query', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ question: userMessage })
      });

      if (!res.ok) throw new Error('Failed to fetch response');

      const data = await res.json();

      setMessages(prev => [...prev, {
        role: 'bot',
        content: data.answer,
        sources: data.sources,
        isSensitive: data.is_sensitive,
        modelUsed: data.model_used
      }]);

    } catch (error) {
      console.error(error);
      setMessages(prev => [...prev, {
        role: 'bot',
        content: 'Sorry, I encountered an error while processing your request. Please try again.'
      }]);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <main className="container">
      <header className="header">
        <h1>PolicyLens</h1>
      </header>

      <div className="chat-container">
        {messages.map((msg, idx) => (
          <div key={idx} className={`message ${msg.role}`}>
            <div className="message-content">
              <div className="markdown-content">
                <ReactMarkdown>{msg.content}</ReactMarkdown>
              </div>

              {msg.modelUsed && (
                <div className="model-info" style={{ fontSize: '0.8rem', color: '#666', marginTop: '4px', fontStyle: 'italic' }}>
                  Generated by {msg.modelUsed}
                </div>
              )}

              {msg.isSensitive && (
                <div className="warning">
                  ⚠️ This topic may be sensitive. Please consult HR for confirmation.
                </div>
              )}

              {msg.sources && msg.sources.length > 0 && (
                <div className="sources">
                  <strong>Sources:</strong>
                  {msg.sources.map((src, i) => (
                    <span key={i} className="source-item">
                      • {src.filename} ({(src.similarity_score * 100).toFixed(0)}% relevance)
                    </span>
                  ))}
                </div>
              )}
            </div>
          </div>
        ))}

        {isLoading && (
          <div className="message bot">
            <div className="loading">
              <div className="dot"></div>
              <div className="dot"></div>
              <div className="dot"></div>
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      <div className="input-area">
        <form onSubmit={handleSubmit} className="input-form">
          <input
            type="text"
            className="input-field"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Ask a question about internal policies..."
          />
          <button type="submit" className="send-button" disabled={isLoading}>
            Send
          </button>
        </form>
      </div>
    </main>
  );
}
